-- Extracted verbatim from ngopen/build_entity_awards.py (SQL_PRIME_AWARDS)
-- Source commit: c4dd142  Extracted: 2026-08-08
DROP MATERIALIZED VIEW IF EXISTS public.prime_awards CASCADE;

CREATE MATERIALIZED VIEW public.prime_awards AS
SELECT 
    ae.entity_id AS linked_entity_id,
    'recipient_hash' AS link_method,
    as_.award_id,
    as_.generated_unique_award_id AS unique_award_id,
    as_.piid,
    as_.fain,
    as_.uri,
    as_.display_award_id,
    as_.category,
    as_.type AS award_type,
    as_.type_description,
    as_.award_amount,
    as_.total_obligation,
    as_.total_subsidy_cost,
    as_.total_loan_value,
    as_.total_outlays,
    as_.original_loan_subsidy_cost,
    as_.face_value_loan_guarantee,
    as_.base_and_all_options_value,
    as_.base_exercised_options_val,
    as_.non_federal_funding_amount,
    as_.action_date,
    as_.fiscal_year,
    as_.date_signed,
    as_.period_of_performance_start_date,
    as_.period_of_performance_current_end_date,
    as_.ordering_period_end_date,
    as_.last_modified_date,
    as_.certified_date,
    as_.create_date,
    as_.update_date,
    as_.recipient_hash,
    as_.recipient_name,
    as_.recipient_unique_id AS recipient_duns,
    as_.recipient_uei,
    as_.parent_recipient_unique_id AS parent_duns,
    as_.parent_uei,
    as_.business_categories,
    as_.recipient_levels,
    as_.recipient_location_country_code AS recipient_country,
    as_.recipient_location_country_name AS recipient_country_name,
    as_.recipient_location_state_code AS recipient_state,
    as_.recipient_location_state_name AS recipient_state_name,
    as_.recipient_location_county_code AS recipient_county_code,
    as_.recipient_location_county_name AS recipient_county_name,
    as_.recipient_location_city_name AS recipient_city,
    as_.recipient_location_zip5 AS recipient_zip5,
    as_.recipient_location_congressional_code AS recipient_congressional_district,
    as_.recipient_location_state_fips AS recipient_state_fips,
    as_.pop_country_code AS pop_country,
    as_.pop_country_name AS pop_country_name,
    as_.pop_state_code AS pop_state,
    as_.pop_state_name AS pop_state_name,
    as_.pop_county_code AS pop_county_code,
    as_.pop_county_name AS pop_county_name,
    as_.pop_city_code AS pop_city_code,
    as_.pop_city_name AS pop_city,
    as_.pop_zip5 AS pop_zip5,
    as_.pop_congressional_code AS pop_congressional_district,
    as_.awarding_agency_id,
    as_.awarding_toptier_agency_name AS awarding_agency,
    as_.awarding_toptier_agency_code AS awarding_agency_code,
    as_.awarding_subtier_agency_name AS awarding_subtier_agency,
    as_.awarding_subtier_agency_code AS awarding_subtier_agency_code,
    as_.funding_agency_id,
    as_.funding_toptier_agency_name AS funding_agency,
    as_.funding_toptier_agency_code AS funding_agency_code,
    as_.funding_subtier_agency_name AS funding_subtier_agency,
    as_.funding_subtier_agency_code AS funding_subtier_agency_code,
    as_.cfda_program_title,
    as_.cfda_number,
    as_.cfdas,
    as_.naics_code,
    as_.naics_description,
    as_.product_or_service_code,
    as_.product_or_service_description,
    as_.type_of_contract_pricing,
    as_.extent_competed,
    as_.type_set_aside,
    as_.sai_number,
    as_.description,
    as_.total_covid_outlay,
    as_.total_covid_obligation,
    as_.disaster_emergency_fund_codes,
    as_.is_fpds,
    as_.total_obl_bin
FROM rpt.award_search as_
JOIN public.all_entities ae ON as_.recipient_hash = ae.recipient_hash;

CREATE UNIQUE INDEX idx_prime_awards_award_id ON public.prime_awards(award_id);
CREATE INDEX idx_prime_awards_linked_entity ON public.prime_awards(linked_entity_id);
CREATE INDEX idx_prime_awards_fiscal_year ON public.prime_awards(fiscal_year);
CREATE INDEX idx_prime_awards_action_date ON public.prime_awards(action_date);
CREATE INDEX idx_prime_awards_recipient_uei ON public.prime_awards(recipient_uei);
CREATE INDEX idx_prime_awards_recipient_state ON public.prime_awards(recipient_state);
CREATE INDEX idx_prime_awards_pop_state ON public.prime_awards(pop_state);
CREATE INDEX idx_prime_awards_total_obligation ON public.prime_awards(total_obligation) WHERE total_obligation > 0;
CREATE INDEX idx_prime_awards_awarding_agency ON public.prime_awards(awarding_agency);
